# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
        - 192.168.0.253/24
      routes:
        - to: default
          via: 192.168.0.1
      nameservers:
          addresses: [192.168.0.253,192.168.0.252,192.168.0.1 ,8.8.8.8]
